import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "../../components/ui/sidebar";
import { AppSidebar } from "../../components/common/app-sidebar";
import { AuthProvider } from "../../context/AuthContext";
import { TaskProvider } from "../../context/TaskContext";
import { UsersProvider } from "../../context/UsersContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <TaskProvider>
        <UsersProvider>
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />
          <main>{children}</main>
        </SidebarProvider>
        </UsersProvider>
      </TaskProvider>
    </AuthProvider>
  );
}
